# Generated by Django 2.0.2 on 2018-02-26 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fish', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fish',
            name='fishDetails',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='fish',
            name='fishTags',
            field=models.TextField(blank=True),
        ),
    ]
