# Generated by Django 2.0.2 on 2018-02-26 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fish',
            fields=[
                ('fishId', models.IntegerField(primary_key=True, serialize=False)),
                ('fishDateTime', models.DateTimeField()),
                ('fishType', models.CharField(choices=[('SALMON', 'Salmon'), ('TUNA', 'Tuna')], max_length=256)),
                ('fishTags', models.TextField()),
                ('fishDetails', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
