/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.fishmodel.Fish', null, global);
goog.exportSymbol('proto.fishmodel.Fish.FishState', null, global);
goog.exportSymbol('proto.fishmodel.Fish.FishType', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.fishmodel.Fish = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.fishmodel.Fish, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.fishmodel.Fish.displayName = 'proto.fishmodel.Fish';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.fishmodel.Fish.prototype.toObject = function(opt_includeInstance) {
  return proto.fishmodel.Fish.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.fishmodel.Fish} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.fishmodel.Fish.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, 0),
    dateTime: jspb.Message.getFieldWithDefault(msg, 2, ""),
    type: jspb.Message.getFieldWithDefault(msg, 3, 0),
    state: jspb.Message.getFieldWithDefault(msg, 4, 0),
    tags: jspb.Message.getFieldWithDefault(msg, 5, ""),
    details: jspb.Message.getFieldWithDefault(msg, 6, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.fishmodel.Fish}
 */
proto.fishmodel.Fish.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.fishmodel.Fish;
  return proto.fishmodel.Fish.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.fishmodel.Fish} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.fishmodel.Fish}
 */
proto.fishmodel.Fish.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setDateTime(value);
      break;
    case 3:
      var value = /** @type {!proto.fishmodel.Fish.FishType} */ (reader.readEnum());
      msg.setType(value);
      break;
    case 4:
      var value = /** @type {!proto.fishmodel.Fish.FishState} */ (reader.readEnum());
      msg.setState(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setTags(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setDetails(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.fishmodel.Fish.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.fishmodel.Fish.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.fishmodel.Fish} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.fishmodel.Fish.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f !== 0) {
    writer.writeUint64(
      1,
      f
    );
  }
  f = message.getDateTime();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getType();
  if (f !== 0.0) {
    writer.writeEnum(
      3,
      f
    );
  }
  f = message.getState();
  if (f !== 0.0) {
    writer.writeEnum(
      4,
      f
    );
  }
  f = message.getTags();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getDetails();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
};


/**
 * @enum {number}
 */
proto.fishmodel.Fish.FishType = {
  TYPE_NONE: 0,
  SALMON: 1,
  TUNA: 2
};

/**
 * @enum {number}
 */
proto.fishmodel.Fish.FishState = {
  STATE_NONE: 0,
  NEW: 1,
  PROCESSING: 2,
  COMPLETED: 3
};

/**
 * optional uint64 id = 1;
 * @return {number}
 */
proto.fishmodel.Fish.prototype.getId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {number} value */
proto.fishmodel.Fish.prototype.setId = function(value) {
  jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional string date_time = 2;
 * @return {string}
 */
proto.fishmodel.Fish.prototype.getDateTime = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.fishmodel.Fish.prototype.setDateTime = function(value) {
  jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional FishType type = 3;
 * @return {!proto.fishmodel.Fish.FishType}
 */
proto.fishmodel.Fish.prototype.getType = function() {
  return /** @type {!proto.fishmodel.Fish.FishType} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/** @param {!proto.fishmodel.Fish.FishType} value */
proto.fishmodel.Fish.prototype.setType = function(value) {
  jspb.Message.setProto3EnumField(this, 3, value);
};


/**
 * optional FishState state = 4;
 * @return {!proto.fishmodel.Fish.FishState}
 */
proto.fishmodel.Fish.prototype.getState = function() {
  return /** @type {!proto.fishmodel.Fish.FishState} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/** @param {!proto.fishmodel.Fish.FishState} value */
proto.fishmodel.Fish.prototype.setState = function(value) {
  jspb.Message.setProto3EnumField(this, 4, value);
};


/**
 * optional string tags = 5;
 * @return {string}
 */
proto.fishmodel.Fish.prototype.getTags = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/** @param {string} value */
proto.fishmodel.Fish.prototype.setTags = function(value) {
  jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional string details = 6;
 * @return {string}
 */
proto.fishmodel.Fish.prototype.getDetails = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/** @param {string} value */
proto.fishmodel.Fish.prototype.setDetails = function(value) {
  jspb.Message.setProto3StringField(this, 6, value);
};


goog.object.extend(exports, proto.fishmodel);
